name: 01 - Building Blocks

on: workflow_dispatch

jobs: 
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello world"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Failed to say bye
        run: |
          echo "hi there"
          exit 1
      - name: say bye
        run: echo "byeeee"

