name: 03-workflow-runners
on: push

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show os
              run: |
                echo "this is the job running on ubuntu runner."
                echo "this is the runner os : $RUNNER_OS"
    windows-echo:
      runs-on: windows-latest
      steps:
        - name: Show OS
          run: |
            echo "this is the job running on windows runner."
            echo "this is the runner OS : $RUNNER_OS"
    
    mac-ech0:
      runs-on: macos-latest

      steps:
        - name: Show-os
          run: |
            echo "this is the job running on mac os"
            echo "this is the runner OS $RUNNER_OS"


