name: 07- using expressions

on: 
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '${{inputs.debug}} Print start-up data'
              if: inputs.debug == true
              run: |
                echo "Triggered by - ${{github.event_name}}"
                echo "Branch - ${{github.ref}}"
                echo "Commit SHA - ${{github.sha}}"
                echo "Runner os - ${{runner.os}}"
            - name: '${{inputs.debug}} Print when triggered from main'
              if: inputs.debug && github.ref == 'refs/heads/main'
              run: echo "I was triggered form main branch"

            